#!/bin/bash

clear

#input
echo "Enter the first number:"
read n1

#menu
echo "Choose an operation:"
echo "1. add"
echo "2. subtract"
echo "3. multiply"
echo "4. divide"
read opr

#more input
echo "Enter the second number:"
read n2

#calculatons and path decisions
if [ $opr = "1" ]
   then
      echo $((n1+n2))
elif [ $opr = "2" ]
   then
      echo $((n1-n2))
elif [ $opr = "3" ]
   then
      echo $((n1*n2))
elif [ $opr = "4" ]
   then
     if [ "$n2" != 0 ]; then
       echo $((n1/n2))
     else
       echo "Division by zero: error."
     fi
fi
